### ISSUE TITLE
Remplacement des Domaines et Activités par des termes plus explicites

### ISSUE THREAD

**Issue by davy39** [Lycee-Experimental/budget-lxp#2]
Pour que le Sunburst soit plus lisible, il faudrait remplacer les domaines et activités comptables par des termes plus explicites : 

Domainess | Intitulés
-- | --
ENS | PÉDAGOGIE
FONCT | FONCTIONNEMENT 

Activités | Intitulés
-- | --
0LEXART | Dépenses artistiques
0LEXDOCUM | Documentation
0LEXPEDAG | Dépenses pédagogiques
0LEXSORTI | Sorties et voyages
0LEXPASS | Assurances
0LEXPCARB | Carburant
0LEXPCONT | Contrats maintenance
0LEXPENT | Entretien/réparation
0LEXPEQ | Petit équipement
0LEXPFOUR | Fournitures
0LEXPHYG | Hygiène
0LEXPLOC | Locations
0LEXPPTT | Timbres, téléphone, internet
0LEXPREC | Frais de réception
0LEXPVEHI | Entretien véhicule
0LEXPVIAB | Viabilisation

Cela peut se faire dans la partie de code de `app.py` suivante :
 
```python
  for _, row in df.iterrows():
        # Récupération des valeurs des colonnes
        domaine = row['Domaine']
        activite = row['Activité']
        libelle_compte = row['Libellé compte']
        fournisseur = row['Nom du fournisseur / élève']
        libelle = row['Libellé 1']
        date = row['Date comptable facture']
        value = row['Prix réceptionné TTC']
```
Il faudrait créer un dictionnaire de type : 
```python
traduction = { 
                      'ENS': 'PÉDAGOGIE', 
                      'FONCT': 'FONCTIONNEMENT',
                      ....... 
                    }
```
et ensuite utiliser la valeur de la colonne à traduire comme **clé** pour obtenir la **valeur** traduite, par exemple : 

```python
domaine = traduction[row['Domaine']]
```

**Comment by Lunanarch** [comment]
C'est fait, je suis trop forte. Rien n'arrêtera la domination du PCE au lycée expérimental de saint-nazaire ! Ah ah ah
