### ISSUE TITLE
Ajout du total au centre du sunburst

### ISSUE THREAD

**Issue by Lunanarch** [Lycee-Experimental/budget-lxp#5]
Ajouter le total du budget dépensé au centre du sunburst, sur le total du budget du lycée

**Comment by davy39** [comment]
Plutôt qu'au centre où il y a peu de place, et le rendrait moins intuitif pour le retour en arrière, je suggère de le faire au dessus ou en dessous du graph.

On pourrait noter un truc du style : 

> **Domaine :** Enseignement (3200€)
> **Activité** : Pédagogique (1340€)
> **Fournisseur** : Carrefour (356€)

En augmentant le niveau de détail au fur et à mesure qu'on descend dans la hierarchie.

J'imagine que le plus simple et de déclarer un `<div id='info'>` vide dans le template, puis de le peupler avec d3 à l'intérieur de la fonction `clicked` qui est lancée à chaque clic au centre ou sur une section : 
```javascript
var info = d3.select("#info")
info.html("code html à rajouter sur la page")
```

Pour le budget total du lycée, je propose de le faire figurer sur un autre graphique, plutot en bare, pour ne pas surcharger d'info le sunbirst.

Bon courage !

**Comment by Lunanarch** [comment]
Ajout des informations en haut à droite (et pas au centre), terminé !
