### ISSUE TITLE
Informations liées au Sunburst

### ISSUE THREAD

**Issue by Lunanarch** [Lycee-Experimental/budget-lxp#7]
- [x] Ajout d'un titre et d'informations au dessus du sunburst
- [x] Ajout d'un pourcentage du budget dépensé par catégorie en-dessous de la partie "Informations". Et egalement une barre de progression totale
- [x] Mise en forme du div info pour qu'il soit responsive

**Comment by Lunanarch** [comment]
Essayer de faire en sorte que la première barre disparaisse en étant en-dehors des childrens (branche luna-dev-3)

**Comment by davy39** [comment]
Bravo pour le div info !
Il faudrait faire en sorte que les div info et graph s'affichent correctement quelque soit la taille de l'écran (sinon le graph est coupé) : 
- Que le div info soit de toute largeur sur les mobiles, et de largeur variable, permettant d'afficher tout le texte sur les PC (au centre ?).
- Que le div chart prenne toute la place restante, et que le graph soit le plus grand possible en fonction de la hauteur et la largeur restante.

**Comment by davy39** [comment]
Hello,
Chez moi le commit 21212e3 ne change pas le fait que le bas du sunburst soit coupé.

**Comment by davy39** [comment]
Ca semble pas mal pour le moment !
